version: '3'
services:
  app:
    build: .
    command: foreman start
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DATABASE_HOST: postgres
    links:
      - postgres
  postgres:
    image: postgres:9.4
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - ../pgdata:/var/lib/postgresql/data