default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: postgres
  host: <%= ENV.fetch('DATABASE_HOST', 'localhost') %>
  template: template0

development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test

production:
  <<: *default
  database: app_production
  username: app
  password: <%= ENV['APP_DATABASE_PASSWORD'] %>